#version: '2'
services:
  session-data:
    image: rbt/session-data:latest
    restart: always
    volumes:
      - /opt/spring-microservices/session-data:/var/local
    ports:
      - "12100:12100"
    network_mode: "host"
