--liquibase formatted sql

--changeset Java:1
--comment create user table
CREATE TABLE public.user
(
    id      int4 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    chat_id int8                                                                                                            NOT NULL,
    "name"  varchar(255) NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
--rollback truncate table user;

--changeset Java:2
--comment create user table
CREATE TABLE public.city
(
    id      int4 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    city    varchar(255) NULL,
    "state" varchar(255) NULL,
    country varchar(255) NULL,
    CONSTRAINT city_pkey PRIMARY KEY (id),
    CONSTRAINT city_name unique (city, "state", country)
);
--rollback truncate table user;