--liquibase formatted sql

--changeset Java:1
--comment create user table
CREATE TABLE public.user
(
    id      int4 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    chat_id int8                                                                                                            NOT NULL,
    "name"  varchar(255) NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
--rollback truncate table user;

--changeset Java:2
--comment create city table
CREATE TABLE public.city
(
    id      int4 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    city    varchar(255) NOT NULL,
    "state" varchar(255) NULL,
    country varchar(255) NULL,
    CONSTRAINT city_pkey PRIMARY KEY (id),
    CONSTRAINT city_name unique (city, "state", country)
);
--rollback truncate table city;

--changeset Java:3
--comment create city_weathermap table
CREATE TABLE public.city_weathermap
(
    id            int4 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    weathermap_id int4 NULL,
    city_id       int4 NULL,
    city          varchar(255) NULL,
    "state"       varchar(255) NULL,
    country       varchar(255) NULL,
    CONSTRAINT city_weathermap_pkey PRIMARY KEY (id),
    CONSTRAINT city_weathermap_name unique (city, "state", country, weathermap_id),
    CONSTRAINT city_weathermap_id unique (weathermap_id),
    CONSTRAINT fk_city_city_weathermap
        FOREIGN KEY (city_id)
            REFERENCES public.city (id)
);
--rollback truncate table city;

--changeset Java:4
--comment insert into city table
INSERT INTO public.city (city) values ('Челябинск');
INSERT INTO public.city_weathermap (weathermap_id, city_id, city, country) values (1508291, 1, 'Chelyabinsk', 'RU');